from . import res_partner
from . import product_template
from . import custom_control
from . import document_document
from . import purchase_order
from . import account_invoice
from . import stock_picking
from . import purchase_custom
from . import shopping_program